// Code generated by generatetestcode.go; DO NOT EDIT.

package recordDefault

import (
	"testing"

	"github.com/rogpeppe/avro/avro-generate-go/internal/testutil"
)

var test = testutil.RoundTripTest{
	InDataJSON: `{}`,
	OutDataJSON: `{
                "recordField": {
                    "F1": 44,
                    "F2": "whee",
                    "F3": "hello"
                }
            }`,
	InSchema: `{
                "name": "R",
                "type": "record",
                "fields": [
                    {
                        "name": "_",
                        "type": "int",
                        "default": 0
                    }
                ]
            }`,
	OutSchema: `{
                "name": "R",
                "type": "record",
                "fields": [
                    {
                        "name": "recordField",
                        "type": {
                            "name": "Foo",
                            "type": "record",
                            "fields": [
                                {
                                    "name": "F1",
                                    "type": "int"
                                },
                                {
                                    "name": "F2",
                                    "type": "string"
                                },
                                {
                                    "name": "F3",
                                    "type": "string",
                                    "default": "hello"
                                }
                            ]
                        },
                        "default": {
                            "F1": 44,
                            "F2": "whee"
                        }
                    }
                ]
            }`,
	GoType: new(R),
}

func TestGeneratedCode(t *testing.T) {
	test.Test(t)
}
