// Code generated by generatetestcode.go; DO NOT EDIT.

package uuid

import (
	"testing"

	"github.com/heetch/avro/cmd/avrogo/internal/testutil"
)

var tests = testutil.RoundTripTest{
	InSchema: `{
                "name": "R",
                "type": "record",
                "fields": [
                    {
                        "name": "T",
                        "type": {
                            "type": "string",
                            "logicalType": "uuid"
                        }
                    }
                ]
            }`,
	GoType: new(R),
	Subtests: []testutil.RoundTripSubtest{{
		TestName: "main",
		InDataJSON: `{
                        "T": "6ba7b810-9dad-11d1-80b4-00c04fd430c8"
                    }`,
		OutDataJSON: `{
                        "T": "6ba7b810-9dad-11d1-80b4-00c04fd430c8"
                    }`,
	}},
}

func TestGeneratedCode(t *testing.T) {
	tests.Test(t)
}
