// Code generated by avrogen. DO NOT EDIT.

package multiSchemaMutualRecursive

import (
	"github.com/heetch/avro/avrotypegen"
)

type S struct {
	Data  string
	Child *R
}

// AvroRecord implements the avro.AvroRecord interface.
func (S) AvroRecord() avrotypegen.RecordInfo {
	return avrotypegen.RecordInfo{
		Schema: `{"fields":[{"default":"","name":"Data","type":"string"},{"default":null,"name":"Child","type":["null",{"fields":[{"default":[],"name":"F","type":{"items":"S","type":"array"}}],"name":"R","type":"record"}]}],"name":"S","type":"record"}`,
	}
}
