// Code generated by avrogen. DO NOT EDIT.

package arrayDefault

import (
	"github.com/heetch/avro/avrotypegen"
)

type R struct {
	ArrayOfInt []int `json:"arrayOfInt"`
}

// AvroRecord implements the avro.AvroRecord interface.
func (R) AvroRecord() avrotypegen.RecordInfo {
	return avrotypegen.RecordInfo{
		Schema: `{"fields":[{"default":[2,3,4],"name":"arrayOfInt","type":{"items":"int","type":"array"}}],"name":"R","type":"record"}`,
		Defaults: []func() interface{}{
			0: func() interface{} {
				return []int{2, 3, 4}
			},
		},
	}
}
