// Code generated by generatetestcode.go; DO NOT EDIT.

package largeRecord

import (
	"testing"

	"github.com/heetch/avro/cmd/avrogo/internal/testutil"
)

var tests = testutil.RoundTripTest{
	InSchema: `{
                "name": "sample",
                "type": "record",
                "fields": [
                    {
                        "name": "header",
                        "type": [
                            "null",
                            {
                                "name": "Data0",
                                "type": "record",
                                "fields": [
                                    {
                                        "name": "uuid",
                                        "type": [
                                            "null",
                                            {
                                                "name": "UUID0",
                                                "type": "record",
                                                "fields": [
                                                    {
                                                        "name": "uuid",
                                                        "type": "string",
                                                        "default": ""
                                                    }
                                                ],
                                                "doc": "A Universally Unique Identifier, in canonical form in lowercase. Example: de305d54-75b4-431b-adb2-eb6b9e546014",
                                                "namespace": "headerworks.datatype"
                                            }
                                        ],
                                        "doc": "Unique identifier for the event used for de-duplication and tracing.",
                                        "default": null
                                    },
                                    {
                                        "name": "hostname",
                                        "type": [
                                            "null",
                                            "string"
                                        ],
                                        "doc": "Fully qualified name of the host that generated the event that generated the data.",
                                        "default": null
                                    },
                                    {
                                        "name": "trace",
                                        "type": [
                                            "null",
                                            {
                                                "name": "Trace0",
                                                "type": "record",
                                                "fields": [
                                                    {
                                                        "name": "traceId",
                                                        "type": [
                                                            "null",
                                                            "headerworks.datatype.UUID0"
                                                        ],
                                                        "doc": "Trace Identifier",
                                                        "default": null
                                                    }
                                                ],
                                                "doc": "Trace0"
                                            }
                                        ],
                                        "doc": "Trace information not redundant with this object",
                                        "default": null
                                    }
                                ],
                                "doc": "Common information related to the event which must be included in any clean event",
                                "namespace": "headerworks"
                            }
                        ],
                        "doc": "Core data information required for any event",
                        "default": null
                    },
                    {
                        "name": "body",
                        "type": [
                            "null",
                            {
                                "name": "Data1",
                                "type": "record",
                                "fields": [
                                    {
                                        "name": "uuid",
                                        "type": [
                                            "null",
                                            {
                                                "name": "UUID1",
                                                "type": "record",
                                                "fields": [
                                                    {
                                                        "name": "uuid",
                                                        "type": "string",
                                                        "default": ""
                                                    }
                                                ],
                                                "doc": "A Universally Unique Identifier, in canonical form in lowercase. Example: de305d54-75b4-431b-adb2-eb6b9e546014",
                                                "namespace": "bodyworks.datatype"
                                            }
                                        ],
                                        "doc": "Unique identifier for the event used for de-duplication and tracing.",
                                        "default": null
                                    },
                                    {
                                        "name": "hostname",
                                        "type": [
                                            "null",
                                            "string"
                                        ],
                                        "doc": "Fully qualified name of the host that generated the event that generated the data.",
                                        "default": null
                                    },
                                    {
                                        "name": "trace",
                                        "type": [
                                            "null",
                                            {
                                                "name": "Trace1",
                                                "type": "record",
                                                "fields": [
                                                    {
                                                        "name": "traceId",
                                                        "type": [
                                                            "null",
                                                            "headerworks.datatype.UUID0"
                                                        ],
                                                        "doc": "Trace Identifier",
                                                        "default": null
                                                    }
                                                ],
                                                "doc": "Trace1"
                                            }
                                        ],
                                        "doc": "Trace information not redundant with this object",
                                        "default": null
                                    }
                                ],
                                "doc": "Common information related to the event which must be included in any clean event",
                                "namespace": "bodyworks"
                            }
                        ],
                        "doc": "Core data information required for any event",
                        "default": null
                    }
                ],
                "doc": "GoGen test",
                "namespace": "com.avro.test"
            }`,
	GoType: new(Sample),
	Subtests: []testutil.RoundTripSubtest{{
		TestName: "main",
		InDataJSON: `{
                        "body": null,
                        "header": {
                            "headerworks.Data0": {
                                "hostname": {
                                    "string": "myhost.com"
                                },
                                "trace": null,
                                "uuid": null
                            }
                        }
                    }`,
		OutDataJSON: `{
                        "body": null,
                        "header": {
                            "headerworks.Data0": {
                                "hostname": {
                                    "string": "myhost.com"
                                },
                                "trace": null,
                                "uuid": null
                            }
                        }
                    }`,
	}},
}

func TestGeneratedCode(t *testing.T) {
	tests.Test(t)
}
