// Code generated by generatetestcode.go; DO NOT EDIT.

package unionInOut

import (
	"testing"

	"github.com/rogpeppe/avro/avro-generate-go/internal/testutil"
)

var test = testutil.RoundTripTest{
	InDataJSON: `{
                "UnionField": {
                    "int": 999
                }
            }`,
	OutDataJSON: `{
                "UnionField": {
                    "int": 999
                }
            }`,
	InSchema: `{
                "name": "PrimitiveUnionTestRecord",
                "type": "record",
                "fields": [
                    {
                        "name": "UnionField",
                        "type": [
                            "int",
                            "long",
                            "float",
                            "double",
                            "string",
                            "boolean",
                            "null"
                        ],
                        "default": 1234
                    }
                ]
            }`,
	OutSchema: `{
                "name": "PrimitiveUnionTestRecord",
                "type": "record",
                "fields": [
                    {
                        "name": "UnionField",
                        "type": [
                            "int",
                            "long",
                            "float",
                            "double",
                            "string",
                            "boolean",
                            "null"
                        ],
                        "default": 1234
                    }
                ]
            }`,
	GoType: new(PrimitiveUnionTestRecord),
}

func TestGeneratedCode(t *testing.T) {
	test.Test(t)
}
