// Code generated by generatetestcode.go; DO NOT EDIT.

package primitiveIncompatible

import (
	"testing"

	"github.com/heetch/avro/cmd/avrogo/internal/testutil"
)

var tests = testutil.RoundTripTest{
	InSchema: `{
                "name": "R",
                "type": "record",
                "fields": [
                    {
                        "name": "f",
                        "type": "int"
                    }
                ]
            }`,
	GoType: new(R),
	Subtests: []testutil.RoundTripSubtest{{
		TestName: "main",
		InDataJSON: `{
                        "f": 2134
                    }`,
		OutDataJSON: `null`,
		ExpectError: map[testutil.ErrorType]string{`unmarshal`: `analysis failed: eval: cannot assign int to string`},
	}},
}

func TestGeneratedCode(t *testing.T) {
	tests.Test(t)
}
