// Code generated by generatetestcode.go; DO NOT EDIT.

package primitiveDefaults

import (
	"testing"

	"github.com/rogpeppe/avro/avro-generate-go/internal/testutil"
)

var tests = testutil.RoundTripTest{
	InSchema: `{
                "name": "R",
                "type": "record",
                "fields": [
                    {
                        "name": "_",
                        "type": "int",
                        "default": 0
                    }
                ]
            }`,
	GoType: new(R),
	Subtests: []testutil.RoundTripSubtest{{
		TestName:   "main",
		InDataJSON: `{}`,
		OutDataJSON: `{
                        "string": "hello",
                        "int": 1111,
                        "long": 2222,
                        "float": 1.5,
                        "double": 2.75,
                        "boolean": true
                    }`,
	}},
}

func TestGeneratedCode(t *testing.T) {
	tests.Test(t)
}
