// Code generated by generatetestcode.go; DO NOT EDIT.

package primitiveDefaults

import (
	"testing"

	"github.com/rogpeppe/avro/avro-generate-go/internal/testutil"
)

var test = testutil.RoundTripTest{
	InDataJSON: `{}`,
	OutDataJSON: `{
                "string": "hello",
                "long": 2222,
                "int": 1111,
                "float": 1.5,
                "double": 2.75,
                "boolean": true
            }`,
	InSchema: `{
                "name": "R",
                "type": "record",
                "fields": [
                    {
                        "name": "_",
                        "type": "int",
                        "default": 0
                    }
                ]
            }`,
	OutSchema: `{
                "name": "R",
                "type": "record",
                "fields": [
                    {
                        "name": "int",
                        "type": "int",
                        "default": 1111
                    },
                    {
                        "name": "long",
                        "type": "long",
                        "default": 2222
                    },
                    {
                        "name": "string",
                        "type": "string",
                        "default": "hello"
                    },
                    {
                        "name": "float",
                        "type": "float",
                        "default": 1.5
                    },
                    {
                        "name": "double",
                        "type": "double",
                        "default": 2.75
                    },
                    {
                        "name": "boolean",
                        "type": "boolean",
                        "default": true
                    }
                ]
            }`,
	GoType: new(R),
}

func TestGeneratedCode(t *testing.T) {
	test.Test(t)
}
