// Code generated by generatetestcode.go; DO NOT EDIT.

package sharedUnion

import (
	"testing"

	"github.com/rogpeppe/avro/avro-generate-go/internal/testutil"
)

var test = testutil.RoundTripTest{
	InDataJSON: `{
                "A": {
                    "int": 244
                },
                "B": {
                    "string": "hello"
                }
            }`,
	OutDataJSON: `{
                "A": {
                    "int": 244
                },
                "B": {
                    "string": "hello"
                }
            }`,
	InSchema: `{
                "name": "R",
                "type": "record",
                "fields": [
                    {
                        "name": "A",
                        "type": [
                            "int",
                            "string",
                            "float"
                        ]
                    },
                    {
                        "name": "B",
                        "type": [
                            "int",
                            "string",
                            "float"
                        ]
                    }
                ]
            }`,
	OutSchema: `{
                "name": "R",
                "type": "record",
                "fields": [
                    {
                        "name": "A",
                        "type": [
                            "int",
                            "string",
                            "float"
                        ]
                    },
                    {
                        "name": "B",
                        "type": [
                            "int",
                            "string",
                            "float"
                        ]
                    }
                ]
            }`,
	GoType: new(R),
}

func TestGeneratedCode(t *testing.T) {
	test.Test(t)
}
