// Code generated by generatetestcode.go; DO NOT EDIT.

package goTypeFixed

import (
	"testing"

	"github.com/rogpeppe/avro/avro-generate-go/internal/testutil"
)

var tests = testutil.RoundTripTest{
	InSchema: `{
                "name": "R",
                "type": "record",
                "fields": [
                    {
                        "name": "A",
                        "type": {
                            "name": "go.Fixed3",
                            "type": "fixed",
                            "size": 3
                        }
                    }
                ]
            }`,
	GoType: new(R),
	Subtests: []testutil.RoundTripSubtest{{
		TestName: "main",
		InDataJSON: `{
                        "A": "abc"
                    }`,
		OutDataJSON: `{
                        "A": "abc"
                    }`,
	}},
}

type R struct {
	A [3]byte
}

func TestGeneratedCode(t *testing.T) {
	tests.Test(t)
}
