// Code generated by generatetestcode.go; DO NOT EDIT.

package goTypeCustomName

import (
	"testing"

	"github.com/heetch/avro/cmd/avrogo/internal/testutil"
)

var tests = testutil.RoundTripTest{
	InSchema: `{
                "name": "M",
                "type": "record",
                "fields": [
                    {
                        "name": "E",
                        "type": {
                            "name": "e",
                            "type": "enum",
                            "symbols": [
                                "a",
                                "b"
                            ],
                            "go.name": "customEnum"
                        }
                    },
                    {
                        "name": "F",
                        "type": {
                            "name": "f",
                            "type": "fixed",
                            "size": 2,
                            "go.name": "customFixed"
                        }
                    }
                ],
                "go.name": "customName"
            }`,
	GoType: new(customName),
	Subtests: []testutil.RoundTripSubtest{{
		TestName: "main",
		InDataJSON: `{
                        "E": "b",
                        "F": "xz"
                    }`,
		OutDataJSON: `{
                        "E": "b",
                        "F": "xz"
                    }`,
	}},
}

func TestGeneratedCode(t *testing.T) {
	tests.Test(t)
}
