// Code generated by generatetestcode.go; DO NOT EDIT.

package simpleGoType

import (
	"testing"

	"github.com/rogpeppe/avro/avro-generate-go/internal/testutil"
)

var test = testutil.RoundTripTest{
	InDataJSON: `{
                "A": 1,
                "B": 2
            }`,
	OutDataJSON: `{
                "A": 1,
                "B": 2
            }`,
	InSchema: `{
                "name": "TestRecord",
                "type": "record",
                "fields": [
                    {
                        "name": "A",
                        "type": "int"
                    },
                    {
                        "name": "B",
                        "type": "int"
                    }
                ]
            }`,
	OutSchema: `null`,
	GoType:    new(TestRecord),
}

type TestRecord struct {
	B int
	A int
}

func TestGeneratedCode(t *testing.T) {
	test.Test(t)
}
