// Code generated by generatetestcode.go; DO NOT EDIT.

package goTypeSimple

import (
	"testing"

	"github.com/rogpeppe/avro/avro-generate-go/internal/testutil"
)

var tests = testutil.RoundTripTest{
	InSchema: `{
                "name": "TestRecord",
                "type": "record",
                "fields": [
                    {
                        "name": "A",
                        "type": "int"
                    },
                    {
                        "name": "B",
                        "type": "int"
                    }
                ]
            }`,
	GoType: new(TestRecord),
	Subtests: []testutil.RoundTripSubtest{{
		TestName: "main",
		InDataJSON: `{
                        "A": 1,
                        "B": 2
                    }`,
		OutDataJSON: `{
                        "A": 1,
                        "B": 2
                    }`,
	}},
}

type TestRecord struct {
	B int
	A int
}

func TestGeneratedCode(t *testing.T) {
	tests.Test(t)
}
