// Code generated by generatetestcode.go; DO NOT EDIT.

package cloudEvent

import (
	"testing"

	"github.com/rogpeppe/avro/avro-generate-go/internal/testutil"
)

var test = testutil.RoundTripTest{
	InDataJSON: `{
                "Metadata": {
                    "time": 12345,
                    "id": "id1",
                    "source": "source1"
                },
                "other": "some other data"
            }`,
	OutDataJSON: `{
                "Metadata": {
                    "time": 12345,
                    "id": "id1",
                    "source": "source1"
                }
            }`,
	InSchema: `{
                "name": "SomeEvent",
                "type": "record",
                "fields": [
                    {
                        "name": "Metadata",
                        "type": {
                            "name": "Metadata",
                            "type": "record",
                            "fields": [
                                {
                                    "name": "id",
                                    "type": "string"
                                },
                                {
                                    "name": "source",
                                    "type": "string"
                                },
                                {
                                    "name": "time",
                                    "type": "long"
                                }
                            ],
                            "namespace": "avro.apache.org"
                        }
                    },
                    {
                        "name": "other",
                        "type": "string"
                    }
                ],
                "namespace": "foo.bar"
            }`,
	OutSchema: `{
                "name": "SomeEvent",
                "type": "record",
                "fields": [
                    {
                        "name": "Metadata",
                        "type": {
                            "name": "Metadata",
                            "type": "record",
                            "fields": [
                                {
                                    "name": "id",
                                    "type": "string"
                                },
                                {
                                    "name": "source",
                                    "type": "string"
                                },
                                {
                                    "name": "time",
                                    "type": "long"
                                }
                            ],
                            "namespace": "avro.apache.org"
                        }
                    }
                ],
                "namespace": "foo.bar",
                "aliases": [
                    "foo.bar.XXXX"
                ]
            }`,
	GoType: new(SomeEvent),
}

func TestGeneratedCode(t *testing.T) {
	test.Test(t)
}
