// Code generated by avrogen. DO NOT EDIT.

package cloudEvent

import "github.com/rogpeppe/avro"

type Metadata struct {
	Id     string `json:"id"`
	Source string `json:"source"`
	Time   int64  `json:"time"`
}

// AvroRecord implements the avro.AvroRecord interface.
func (Metadata) AvroRecord() avro.RecordInfo {
	return avro.RecordInfo{
		Schema: `{"fields":[{"name":"id","type":"string"},{"name":"source","type":"string"},{"name":"time","type":"long"}],"name":"Metadata","namespace":"avro.apache.org","type":"record"}`,
	}
}

// TODO implement MarshalBinary and UnmarshalBinary methods?

type SomeEvent struct {
	Metadata Metadata
}

// AvroRecord implements the avro.AvroRecord interface.
func (SomeEvent) AvroRecord() avro.RecordInfo {
	return avro.RecordInfo{
		Schema: `{"aliases":["foo.bar.XXXX"],"fields":[{"name":"Metadata","type":{"fields":[{"name":"id","type":"string"},{"name":"source","type":"string"},{"name":"time","type":"long"}],"name":"Metadata","namespace":"avro.apache.org","type":"record"}}],"name":"SomeEvent","namespace":"foo.bar","type":"record"}`,
	}
}

// TODO implement MarshalBinary and UnmarshalBinary methods?

// Alias foo.bar.XXXX = foo.bar.SomeEvent
