// Code generated by generatetestcode.go; DO NOT EDIT.

package unionNullStringReverse

import (
	"testing"

	"github.com/heetch/avro/cmd/avro-generate-go/internal/testutil"
)

var tests = testutil.RoundTripTest{
	InSchema: `{
                "name": "R",
                "type": "record",
                "fields": [
                    {
                        "name": "OptionalString",
                        "type": [
                            "string",
                            "null"
                        ]
                    }
                ]
            }`,
	GoType: new(R),
	Subtests: []testutil.RoundTripSubtest{{
		TestName: "withNull",
		InDataJSON: `{
                        "OptionalString": null
                    }`,
		OutDataJSON: `{
                        "OptionalString": null
                    }`,
	}, {
		TestName: "withString",
		InDataJSON: `{
                        "OptionalString": {
                            "string": "hello"
                        }
                    }`,
		OutDataJSON: `{
                        "OptionalString": {
                            "string": "hello"
                        }
                    }`,
	}},
}

func TestGeneratedCode(t *testing.T) {
	tests.Test(t)
}
