// Code generated by avrogen. DO NOT EDIT.

package simpleFixed

import "github.com/heetch/avro/avrotypegen"

type R struct {
	F Five
}

// AvroRecord implements the avro.AvroRecord interface.
func (R) AvroRecord() avrotypegen.RecordInfo {
	return avrotypegen.RecordInfo{
		Schema: `{"fields":[{"name":"F","type":{"name":"five","size":5,"type":"fixed"}}],"name":"R","type":"record"}`,
		Required: []bool{
			0: true,
		},
	}
}

// TODO implement MarshalBinary and UnmarshalBinary methods?

type Five [5]byte
