// Code generated by generatetestcode.go; DO NOT EDIT.

package duplicateRecord

import (
	"testing"

	"github.com/heetch/avro/cmd/avrogo/internal/testutil"
)

var tests = testutil.RoundTripTest{
	InSchema: `{
                "name": "R1",
                "type": "record",
                "fields": [
                    {
                        "name": "F",
                        "type": {
                            "name": "R2",
                            "type": "record",
                            "fields": [
                                {
                                    "name": "A",
                                    "type": "string"
                                }
                            ]
                        }
                    },
                    {
                        "name": "G",
                        "type": "R2"
                    },
                    {
                        "name": "H",
                        "type": "int"
                    }
                ]
            }`,
	GoType: new(R1),
	Subtests: []testutil.RoundTripSubtest{{
		TestName: "main",
		InDataJSON: `{
                        "F": {
                            "A": "hello"
                        },
                        "G": {
                            "A": "goodbye"
                        },
                        "H": 99
                    }`,
		OutDataJSON: `{
                        "F": {
                            "A": "hello"
                        },
                        "G": {
                            "A": "goodbye"
                        },
                        "H": 99
                    }`,
	}},
}

func TestGeneratedCode(t *testing.T) {
	tests.Test(t)
}
