// Code generated by generatetestcode.go; DO NOT EDIT.

package mapDefault

import (
	"testing"

	"github.com/rogpeppe/avro/avro-generate-go/internal/testutil"
)

var test = testutil.RoundTripTest{
	InDataJSON: `{}`,
	OutDataJSON: `{
                "mapOfInt": {
                    "a": 2,
                    "b": 5,
                    "c": 99
                }
            }`,
	InSchema: `{
                "name": "R",
                "type": "record",
                "fields": [
                    {
                        "name": "_",
                        "type": "int",
                        "default": 0
                    }
                ]
            }`,
	OutSchema: `{
                "name": "R",
                "type": "record",
                "fields": [
                    {
                        "name": "mapOfInt",
                        "type": {
                            "type": "map",
                            "values": "int"
                        },
                        "default": {
                            "a": 2,
                            "b": 5,
                            "c": 99
                        }
                    }
                ]
            }`,
	GoType: new(R),
}

func TestGeneratedCode(t *testing.T) {
	test.Test(t)
}
