// Code generated by avrogen. DO NOT EDIT.

package mapDefault

import "github.com/rogpeppe/avro"

type R struct {
	MapOfInt map[string]int `json:"mapOfInt"`
}

// AvroRecord implements the avro.AvroRecord interface.
func (R) AvroRecord() avro.RecordInfo {
	return avro.RecordInfo{
		Schema: `{"fields":[{"default":{"a":2,"b":5,"c":99},"name":"mapOfInt","type":{"type":"map","values":"int"}}],"name":"R","type":"record"}`,
		Fields: []avro.FieldInfo{
			0: {
				Default: func() interface{} {
					return map[string]int{
						"a": 2,
						"b": 5,
						"c": 99,
					}
				},
			},
		},
	}
}

// TODO implement MarshalBinary and UnmarshalBinary methods?
