// Code generated by avrogen. DO NOT EDIT.

package mapDefault

import (
	"github.com/heetch/avro/avrotypegen"
)

type R struct {
	MapOfInt map[string]int `json:"mapOfInt"`
}

// AvroRecord implements the avro.AvroRecord interface.
func (R) AvroRecord() avrotypegen.RecordInfo {
	return avrotypegen.RecordInfo{
		Schema: `{"fields":[{"default":{"a":2,"b":5,"c":99},"name":"mapOfInt","type":{"type":"map","values":"int"}}],"name":"R","type":"record"}`,
		Defaults: []func() interface{}{
			0: func() interface{} {
				return map[string]int{
					"a": 2,
					"b": 5,
					"c": 99,
				}
			},
		},
	}
}

// TODO implement MarshalBinary and UnmarshalBinary methods?
