package generate

import (
	"tool/file"
	"encoding/yaml"
	"github.com/heetch/cue-schema/github/workflow"
)

Workflow :: workflow

command: generateworkflow: {
	task: write: file.Create & {
		filename: ".github/workflows/test.yaml"
		contents: """
			// Code generated by github.com/heetch/cue-schema/github/workflow/generate. DO NOT EDIT.
			\(yaml.Marshal(Workflow))
		"""
	}
}
