// Code generated by generatetestcode.go; DO NOT EDIT.

package recordWithDefaultNotPresent

import (
	"testing"

	"github.com/rogpeppe/avro/avro-generate-go/internal/testutil"
)

var tests = testutil.RoundTripTest{
	InSchema: `{
                "name": "R",
                "type": "record",
                "fields": [
                    {
                        "name": "A",
                        "type": "int",
                        "default": 99
                    }
                ]
            }`,
	GoType: new(R),
	Subtests: []testutil.RoundTripSubtest{{
		TestName:   "main",
		InDataJSON: `{}`,
		OutDataJSON: `{
                        "A": 99
                    }`,
	}},
}

func TestGeneratedCode(t *testing.T) {
	tests.Test(t)
}
