// Code generated by avrogen. DO NOT EDIT.

package unionToScalar

import "github.com/rogpeppe/avro"

type PrimitiveUnionTestRecord struct {
	UnionField int
}

// AvroRecord implements the avro.AvroRecord interface.
func (PrimitiveUnionTestRecord) AvroRecord() avro.RecordInfo {
	return avro.RecordInfo{
		Schema: `{"fields":[{"default":1234,"name":"UnionField","type":"int"}],"name":"PrimitiveUnionTestRecord","type":"record"}`,
		Fields: []avro.FieldInfo{
			0: {
				Default: func() interface{} {
					return 1234
				},
			},
		},
	}
}

// TODO implement MarshalBinary and UnmarshalBinary methods?
