// Code generated by avrogen. DO NOT EDIT.

package unionNullStringReverseWithNull

import "github.com/heetch/avro/avrotypegen"

type R struct {
	OptionalString *string
}

// AvroRecord implements the avro.AvroRecord interface.
func (R) AvroRecord() avrotypegen.RecordInfo {
	return avrotypegen.RecordInfo{
		Schema: `{"fields":[{"name":"OptionalString","type":["string","null"]}],"name":"R","type":"record"}`,
		Required: []bool{
			0: true,
		},
		Unions: [][]interface{}{
			0: {new(string), nil},
		},
	}
}

// TODO implement MarshalBinary and UnmarshalBinary methods?
