// Code generated by generatetestcode.go; DO NOT EDIT.

package primitive

import (
	"testing"

	"github.com/heetch/avro/cmd/avrogo/internal/testutil"
)

var tests = testutil.RoundTripTest{
	InSchema: `{
                "name": "R",
                "type": "record",
                "fields": [
                    {
                        "name": "intField",
                        "type": "int"
                    },
                    {
                        "name": "longField",
                        "type": "long"
                    },
                    {
                        "name": "floatField",
                        "type": "float"
                    },
                    {
                        "name": "doubleField",
                        "type": "double"
                    },
                    {
                        "name": "boolField",
                        "type": "boolean"
                    },
                    {
                        "name": "bytesField",
                        "type": "bytes"
                    },
                    {
                        "name": "stringField",
                        "type": "string"
                    },
                    {
                        "name": "nullField",
                        "type": "null"
                    }
                ]
            }`,
	GoType: new(R),
	Subtests: []testutil.RoundTripSubtest{{
		TestName: "highValues",
		InDataJSON: `{
                        "intField": 2147483647,
                        "longField": 9223372036854775807,
                        "floatField": 2E-10,
                        "doubleField": 2E-50,
                        "boolField": true,
                        "bytesField": "stuff",
                        "stringField": "hello world",
                        "nullField": null
                    }`,
		OutDataJSON: `{
                        "intField": 2147483647,
                        "longField": 9223372036854775807,
                        "floatField": 2E-10,
                        "doubleField": 2E-50,
                        "boolField": true,
                        "bytesField": "stuff",
                        "stringField": "hello world",
                        "nullField": null
                    }`,
	}, {
		TestName: "lowValues",
		InDataJSON: `{
                        "intField": -2147483648,
                        "longField": -9223372036854775808,
                        "floatField": -2E-10,
                        "doubleField": -2E-50,
                        "boolField": false,
                        "bytesField": "",
                        "stringField": "",
                        "nullField": null
                    }`,
		OutDataJSON: `{
                        "intField": -2147483648,
                        "longField": -9223372036854775808,
                        "floatField": -2E-10,
                        "doubleField": -2E-50,
                        "boolField": false,
                        "bytesField": "",
                        "stringField": "",
                        "nullField": null
                    }`,
	}},
}

func TestGeneratedCode(t *testing.T) {
	tests.Test(t)
}
