// Code generated by generatetestcode.go; DO NOT EDIT.

package simpleInUnionOut

import (
	"testing"

	"github.com/heetch/avro/cmd/avro-generate-go/internal/testutil"
)

var tests = testutil.RoundTripTest{
	InSchema: `{
                "name": "R",
                "type": "record",
                "fields": [
                    {
                        "name": "UnionField",
                        "type": "string"
                    }
                ]
            }`,
	GoType: new(R),
	Subtests: []testutil.RoundTripSubtest{{
		TestName: "main",
		InDataJSON: `{
                        "UnionField": "hello"
                    }`,
		OutDataJSON: `{
                        "UnionField": {
                            "string": "hello"
                        }
                    }`,
	}},
}

func TestGeneratedCode(t *testing.T) {
	tests.Test(t)
}
