// Code generated by generatetestcode.go; DO NOT EDIT.

package goTypeSlice

import (
	"testing"

	"github.com/heetch/avro/avro-generate-go/internal/testutil"
)

var tests = testutil.RoundTripTest{
	InSchema: `{
                "name": "R",
                "type": "record",
                "fields": [
                    {
                        "name": "A",
                        "type": {
                            "type": "array",
                            "items": "string"
                        }
                    }
                ]
            }`,
	GoType: new(R),
	Subtests: []testutil.RoundTripSubtest{{
		TestName: "empty",
		InDataJSON: `{
                        "A": []
                    }`,
		OutDataJSON: `{
                        "A": []
                    }`,
	}, {
		TestName: "non_empty",
		InDataJSON: `{
                        "A": [
                            "a",
                            "b",
                            "cd"
                        ]
                    }`,
		OutDataJSON: `{
                        "A": [
                            "a",
                            "b",
                            "cd"
                        ]
                    }`,
	}},
}

type R struct {
	A []string
}

func TestGeneratedCode(t *testing.T) {
	tests.Test(t)
}
