// Code generated by generatetestcode.go; DO NOT EDIT.

package enumDefault

import (
	"testing"

	"github.com/rogpeppe/avro/avro-generate-go/internal/testutil"
)

var test = testutil.RoundTripTest{
	InDataJSON: `{}`,
	OutDataJSON: `{
                "enumField": "b"
            }`,
	InSchema: `{
                "name": "R",
                "type": "record",
                "fields": [
                    {
                        "name": "_",
                        "type": "int",
                        "default": 0
                    }
                ]
            }`,
	OutSchema: `{
                "name": "R",
                "type": "record",
                "fields": [
                    {
                        "name": "enumField",
                        "type": {
                            "name": "Foo",
                            "type": "enum",
                            "symbols": [
                                "a",
                                "b",
                                "c"
                            ]
                        },
                        "default": "b"
                    }
                ]
            }`,
	GoType: new(R),
}

func TestGeneratedCode(t *testing.T) {
	test.Test(t)
}
