// Code generated by avrogen. DO NOT EDIT.

package enumDefault

import "github.com/rogpeppe/avro"

type Foo int

const (
	FooA Foo = iota
	FooB
	FooC
)

// TODO UnmarshalText and String methods.

type R struct {
	EnumField Foo `json:"enumField"`
}

// AvroRecord implements the avro.AvroRecord interface.
func (R) AvroRecord() avro.RecordInfo {
	return avro.RecordInfo{
		Schema: `{"fields":[{"default":"b","name":"enumField","type":{"name":"Foo","symbols":["a","b","c"],"type":"enum"}}],"name":"R","type":"record"}`,
		Defaults: []func() interface{}{
			0: func() interface{} {
				return FooB
			},
		},
	}
}

// TODO implement MarshalBinary and UnmarshalBinary methods?
