// Code generated by generatetestcode.go; DO NOT EDIT.

package justEnum

import (
	"testing"

	"github.com/heetch/avro/cmd/avrogo/internal/testutil"
)

var tests = testutil.RoundTripTest{
	InSchema: `{
                "name": "MyEnum",
                "type": "enum",
                "symbols": [
                    "a",
                    "b",
                    "c"
                ]
            }`,
	GoType: new(MyEnum),
	Subtests: []testutil.RoundTripSubtest{{
		TestName:    "main",
		InDataJSON:  `"b"`,
		OutDataJSON: `"b"`,
	}},
}

func TestGeneratedCode(t *testing.T) {
	tests.Test(t)
}
