// Code generated by generatetestcode.go; DO NOT EDIT.

package unionNullStringWithString

import (
	"testing"

	"github.com/rogpeppe/avro/avro-generate-go/internal/testutil"
)

var test = testutil.RoundTripTest{
	InDataJSON: `{
                "OptionalString": {
                    "string": "hello"
                }
            }`,
	OutDataJSON: `{
                "OptionalString": {
                    "string": "hello"
                }
            }`,
	InSchema: `{
                "name": "R",
                "type": "record",
                "fields": [
                    {
                        "name": "OptionalString",
                        "type": [
                            "null",
                            "string"
                        ]
                    }
                ]
            }`,
	OutSchema: `{
                "name": "R",
                "type": "record",
                "fields": [
                    {
                        "name": "OptionalString",
                        "type": [
                            "null",
                            "string"
                        ]
                    }
                ]
            }`,
	GoType: new(R),
}

func TestGeneratedCode(t *testing.T) {
	test.Test(t)
}
