// Code generated by avrogen. DO NOT EDIT.

package unionNullStringWithString

import "github.com/rogpeppe/avro"

type R struct {
	OptionalString *string
}

// AvroRecord implements the avro.AvroRecord interface.
func (R) AvroRecord() avro.RecordInfo {
	return avro.RecordInfo{
		Schema: `{"fields":[{"name":"OptionalString","type":["null","string"]}],"name":"R","type":"record"}`,
		Fields: []avro.FieldInfo{
			0: {
				Info: &avro.TypeInfo{
					Type: new(*string),
					Union: []avro.TypeInfo{{}, {
						Type: new(string),
					}},
				},
			},
		},
	}
}

// TODO implement MarshalBinary and UnmarshalBinary methods?
