// Code generated by generatetestcode.go; DO NOT EDIT.

package arrayDefault

import (
	"testing"

	"github.com/rogpeppe/avro/avro-generate-go/internal/testutil"
)

var test = testutil.RoundTripTest{
	InDataJSON: `{}`,
	OutDataJSON: `{
                "arrayOfInt": [
                    2,
                    3,
                    4
                ]
            }`,
	InSchema: `{
                "name": "R",
                "type": "record",
                "fields": [
                    {
                        "name": "_",
                        "type": "int",
                        "default": 0
                    }
                ]
            }`,
	OutSchema: `{
                "name": "R",
                "type": "record",
                "fields": [
                    {
                        "name": "arrayOfInt",
                        "type": {
                            "type": "array",
                            "items": "int"
                        },
                        "default": [
                            2,
                            3,
                            4
                        ]
                    }
                ]
            }`,
	GoType: new(R),
}

func TestGeneratedCode(t *testing.T) {
	test.Test(t)
}
