// Code generated by generatetestcode.go; DO NOT EDIT.

package arrayOfUnion

import (
	"testing"

	"github.com/rogpeppe/avro/avro-generate-go/internal/testutil"
)

var tests = testutil.RoundTripTest{
	InSchema: `{
                "name": "R",
                "type": "record",
                "fields": [
                    {
                        "name": "F",
                        "type": {
                            "type": "array",
                            "items": [
                                "int",
                                "string"
                            ]
                        }
                    }
                ]
            }`,
	GoType: new(R),
	Subtests: []testutil.RoundTripSubtest{{
		TestName: "main",
		InDataJSON: `{
                        "F": [
                            {
                                "int": 1
                            },
                            {
                                "string": "hello"
                            }
                        ]
                    }`,
		OutDataJSON: `{
                        "F": [
                            {
                                "int": 1
                            },
                            {
                                "string": "hello"
                            }
                        ]
                    }`,
	}},
}

func TestGeneratedCode(t *testing.T) {
	tests.Test(t)
}
