// Code generated by generatetestcode.go; DO NOT EDIT.

package goTypeFieldsOmitted

import (
	"testing"

	"github.com/heetch/avro/cmd/avrogo/internal/testutil"
)

var tests = testutil.RoundTripTest{
	InSchema: `{
                "name": "R",
                "type": "record",
                "fields": []
            }`,
	GoType: new(R),
	Subtests: []testutil.RoundTripSubtest{{
		TestName:   "main",
		InDataJSON: `{}`,
		OutDataJSON: `{
                        "E": [],
                        "A": 0,
                        "F": {
                            "A": 0,
                            "B": ""
                        },
                        "B": "",
                        "C": "\u0000\u0000\u0000",
                        "D": {}
                    }`,
	}},
}

type R struct {
	A int
	B string
	C [3]byte
	D map[string]string
	E []string
	F T
}
type T struct {
	A int
	B string
}

func TestGeneratedCode(t *testing.T) {
	tests.Test(t)
}
