// Code generated by generatetestcode.go; DO NOT EDIT.

package unionIntVsLong

import (
	"testing"

	"github.com/rogpeppe/avro/avro-generate-go/internal/testutil"
)

var tests = testutil.RoundTripTest{
	InSchema: `{
                "name": "R",
                "type": "record",
                "fields": [
                    {
                        "name": "F",
                        "type": [
                            "int",
                            "string"
                        ],
                        "default": 1234
                    }
                ]
            }`,
	GoType: new(R),
	Subtests: []testutil.RoundTripSubtest{{
		TestName: "main",
		InDataJSON: `{
                        "F": {
                            "int": 999
                        }
                    }`,
		OutDataJSON: `{
                        "F": {
                            "long": 999
                        }
                    }`,
	}},
}

func TestGeneratedCode(t *testing.T) {
	tests.Test(t)
}
