// Code generated by avrogen. DO NOT EDIT.

package unionIntVsLong

import (
	"github.com/heetch/avro/avrotypegen"
)

type R struct {
	F interface{}
}

// AvroRecord implements the avro.AvroRecord interface.
func (R) AvroRecord() avrotypegen.RecordInfo {
	return avrotypegen.RecordInfo{
		Schema: `{"fields":[{"default":1234,"name":"F","type":["long","int","string"]}],"name":"R","type":"record"}`,
		Defaults: []func() interface{}{
			0: func() interface{} {
				return int64(1234)
			},
		},
		Unions: [][]interface{}{
			0: {new(int64), new(int), new(string)},
		},
	}
}

// TODO implement MarshalBinary and UnmarshalBinary methods?
