// Code generated by avrogen. DO NOT EDIT.

package unionNullStringWithNull

import "github.com/heetch/avro/avrotypegen"

type R struct {
	OptionalString *string
}

// AvroRecord implements the avro.AvroRecord interface.
func (R) AvroRecord() avrotypegen.RecordInfo {
	return avrotypegen.RecordInfo{
		Schema: `{"fields":[{"name":"OptionalString","type":["null","string"]}],"name":"R","type":"record"}`,
		Required: []bool{
			0: true,
		},
		Unions: [][]interface{}{
			0: {nil, new(string)},
		},
	}
}

// TODO implement MarshalBinary and UnmarshalBinary methods?
