// Code generated by "stringer -type Enum -trimprefix Enum"; DO NOT EDIT.

package testtypes

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EnumOne-0]
	_ = x[EnumTwo-1]
	_ = x[EnumThree-2]
}

const _Enum_name = "OneTwoThree"

var _Enum_index = [...]uint8{0, 3, 6, 11}

func (i Enum) String() string {
	if i < 0 || i >= Enum(len(_Enum_index)-1) {
		return "Enum(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Enum_name[_Enum_index[i]:_Enum_index[i+1]]
}
