// Code generated by avrogen. DO NOT EDIT.

package primitive

import "github.com/rogpeppe/avro/avrotypegen"

type R struct {
	IntField    int     `json:"intField"`
	LongField   int64   `json:"longField"`
	FloatField  float32 `json:"floatField"`
	DoubleField float64 `json:"doubleField"`
	BoolField   bool    `json:"boolField"`
	BytesField  []byte  `json:"bytesField"`
	StringField string  `json:"stringField"`
}

// AvroRecord implements the avro.AvroRecord interface.
func (R) AvroRecord() avrotypegen.RecordInfo {
	return avrotypegen.RecordInfo{
		Schema: `{"fields":[{"name":"intField","type":"int"},{"name":"longField","type":"long"},{"name":"floatField","type":"float"},{"name":"doubleField","type":"double"},{"name":"boolField","type":"boolean"},{"name":"bytesField","type":"bytes"},{"name":"stringField","type":"string"}],"name":"R","type":"record"}`,
		Required: []bool{
			0: true,
			1: true,
			2: true,
			3: true,
			4: true,
			5: true,
			6: true,
		},
	}
}

// TODO implement MarshalBinary and UnmarshalBinary methods?
