// Code generated by avrogen. DO NOT EDIT.

package fixedDefault

import "github.com/heetch/avro/avrotypegen"

type R struct {
	FixedField Five `json:"fixedField"`
}

// AvroRecord implements the avro.AvroRecord interface.
func (R) AvroRecord() avrotypegen.RecordInfo {
	return avrotypegen.RecordInfo{
		Schema: `{"fields":[{"default":"hello","name":"fixedField","type":{"name":"five","size":5,"type":"fixed"}}],"name":"R","type":"record"}`,
		Defaults: []func() interface{}{
			0: func() interface{} {
				return Five{0x68, 0x65, 0x6c, 0x6c, 0x6f}
			},
		},
	}
}

// TODO implement MarshalBinary and UnmarshalBinary methods?

type Five [5]byte
