// Code generated by avrogen. DO NOT EDIT.

package emptyRecord

import (
	"github.com/heetch/avro/avrotypegen"
)

type R struct {
}

// AvroRecord implements the avro.AvroRecord interface.
func (R) AvroRecord() avrotypegen.RecordInfo {
	return avrotypegen.RecordInfo{
		Schema: `{"fields":[{"default":null,"name":"_","type":"null"}],"name":"R","type":"record"}`,
	}
}
