// +build ignore

package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"io/ioutil"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"text/template"
)

var testCodeTemplate = template.Must(
	template.New("").
		Delims("«", "»").
		Funcs(template.FuncMap{
			"quote": quote,
		}).
		Parse(`
// Code generated by generatetestcode.go; DO NOT EDIT.

package «.TestName»

import (
	"testing"

	"github.com/rogpeppe/avro/avro-generate-go/internal/testutil"
)

var test = testutil.RoundTripTest{
	InDataJSON: «quote .InData»,
	OutDataJSON: «quote .OutData»,
	InSchema: «quote .InSchema»,
	OutSchema: «quote .OutSchema»,
	GoType: new(«.GoType»),
}

«if .GoTypeBody -»
type «.GoType» «.GoTypeBody»
«end»

func TestGeneratedCode(t *testing.T) {
	test.Test(t)
}
`[1:]))

const generateDir = "internal/generated_tests"

type testData struct {
	TestName   string          `json:"testName"`
	InSchema   json.RawMessage `json:"inSchema"`
	OutSchema  json.RawMessage `json:"outSchema"`
	GoType     string          `json:"goType"`
	GoTypeBody string          `json:"goTypeBody"`
	InData     json.RawMessage `json:"inData"`
	OutData    json.RawMessage `json:"outData"`
}

func main() {
	var exported struct {
		Tests map[string]testData `json:"tests"`
	}
	var buf bytes.Buffer
	cmd := exec.Command("cue", "export")
	cmd.Dir = "./testdata"
	cmd.Stderr = os.Stderr
	cmd.Stdout = &buf
	err := cmd.Run()
	check("run cue export", err)
	err = json.Unmarshal(buf.Bytes(), &exported)
	if err != nil {
		log.Printf("bad export data: %q", buf.Bytes())
	}
	check("unmarshal test data", err)
	os.RemoveAll(generateDir)
	for _, test := range exported.Tests {
		dir := filepath.Join(generateDir, test.TestName)
		err := os.MkdirAll(dir, 0777)
		check("mkdir", err)
		if !bytes.Equal(test.OutSchema, []byte(`null`)) {
			file := filepath.Join(dir, "schema.avsc")
			err = ioutil.WriteFile(file, []byte(test.OutSchema), 0666)
			check("create schema file", err)

			cmd := exec.Command("avro-generate-go", "-p", test.TestName, "schema.avsc")
			cmd.Stderr = os.Stderr
			cmd.Stdout = os.Stdout
			cmd.Dir = dir
			err = cmd.Run()
			check("avro-generate-go "+file, err)
		}
		var buf bytes.Buffer
		err = testCodeTemplate.Execute(&buf, test)
		check("generate test code", err)
		goSource, err := format.Source(buf.Bytes())
		check("gofmt test code", err)
		err = ioutil.WriteFile(filepath.Join(dir, "roundtrip_test.go"), goSource, 0666)
		check("write test go file", err)
	}
}

func check(what string, err error) {
	if err != nil {
		fmt.Fprintf(os.Stderr, "generatetestcode: %s: %v\n", what, err)
		os.Exit(1)
	}
}

func quote(b []byte) string {
	s := string(b)
	if !strings.Contains(s, "`") {
		return "`" + s + "`"
	}
	return strconv.Quote(s)
}
