// Code generated by generatetestcode.go; DO NOT EDIT.

package simpleMap

import (
	"testing"

	"github.com/heetch/avro/cmd/avro-generate-go/internal/testutil"
)

var tests = testutil.RoundTripTest{
	InSchema: `{
                "name": "R",
                "type": "record",
                "fields": [
                    {
                        "name": "M",
                        "type": {
                            "type": "map",
                            "values": "int"
                        }
                    }
                ]
            }`,
	GoType: new(R),
	Subtests: []testutil.RoundTripSubtest{{
		TestName: "empty",
		InDataJSON: `{
                        "M": {}
                    }`,
		OutDataJSON: `{
                        "M": {}
                    }`,
	}, {
		TestName: "non_empty",
		InDataJSON: `{
                        "M": {
                            "a": 32,
                            "b": 54
                        }
                    }`,
		OutDataJSON: `{
                        "M": {
                            "a": 32,
                            "b": 54
                        }
                    }`,
	}},
}

func TestGeneratedCode(t *testing.T) {
	tests.Test(t)
}
