// Code generated by generatetestcode.go; DO NOT EDIT.

package goTypeProtobufRecord

import (
	"testing"

	"github.com/heetch/avro/cmd/avrogo/internal/testutil"
)

var tests = testutil.RoundTripTest{
	InSchema: `{
                "name": "MessageB",
                "type": "record",
                "fields": [
                    {
                        "name": "dummy",
                        "type": "string"
                    }
                ]
            }`,
	GoType: new(R),
	Subtests: []testutil.RoundTripSubtest{{
		TestName: "main",
		InDataJSON: `{
                        "dummy": ""
                    }`,
		OutDataJSON: `{
                        "arble": null,
                        "selected": false
                    }`,
	}},
}

func TestGeneratedCode(t *testing.T) {
	tests.Test(t)
}
