// Code generated by avrogen. DO NOT EDIT.

package timestampMicros

import (
	"github.com/heetch/avro/avrotypegen"
	"time"
)

type R struct {
	T time.Time
}

// AvroRecord implements the avro.AvroRecord interface.
func (R) AvroRecord() avrotypegen.RecordInfo {
	return avrotypegen.RecordInfo{
		Schema: `{"fields":[{"name":"T","type":{"logicalType":"timestamp-micros","type":"long"}}],"name":"R","type":"record"}`,
		Required: []bool{
			0: true,
		},
	}
}
