// Code generated by generatetestcode.go; DO NOT EDIT.

package simpleMap

import (
	"testing"

	"github.com/rogpeppe/avro/avro-generate-go/internal/testutil"
)

var test = testutil.RoundTripTest{
	InDataJSON: `{
                "M": {
                    "a": 32,
                    "b": 54
                }
            }`,
	OutDataJSON: `{
                "M": {
                    "a": 32,
                    "b": 54
                }
            }`,
	InSchema: `{
                "name": "R",
                "type": "record",
                "fields": [
                    {
                        "name": "M",
                        "type": {
                            "type": "map",
                            "values": "int"
                        }
                    }
                ]
            }`,
	OutSchema: `{
                "name": "R",
                "type": "record",
                "fields": [
                    {
                        "name": "M",
                        "type": {
                            "type": "map",
                            "values": "int"
                        }
                    }
                ]
            }`,
	GoType: new(R),
}

func TestGeneratedCode(t *testing.T) {
	test.Test(t)
}
