// Code generated by avrogen. DO NOT EDIT.

package simpleMap

import "github.com/heetch/avro/avrotypegen"

type R struct {
	M map[string]int
}

// AvroRecord implements the avro.AvroRecord interface.
func (R) AvroRecord() avrotypegen.RecordInfo {
	return avrotypegen.RecordInfo{
		Schema: `{"fields":[{"name":"M","type":{"type":"map","values":"int"}}],"name":"R","type":"record"}`,
		Required: []bool{
			0: true,
		},
	}
}

// TODO implement MarshalBinary and UnmarshalBinary methods?
