// Code generated by generatetestcode.go; DO NOT EDIT.

package goTypeMap

import (
	"testing"

	"github.com/heetch/avro/avro-generate-go/internal/testutil"
)

var tests = testutil.RoundTripTest{
	InSchema: `{
                "name": "R",
                "type": "record",
                "fields": [
                    {
                        "name": "A",
                        "type": {
                            "type": "map",
                            "values": "string"
                        }
                    }
                ]
            }`,
	GoType: new(R),
	Subtests: []testutil.RoundTripSubtest{{
		TestName: "empty",
		InDataJSON: `{
                        "A": {}
                    }`,
		OutDataJSON: `{
                        "A": {}
                    }`,
	}, {
		TestName: "non_empty",
		InDataJSON: `{
                        "A": {
                            "a": "b",
                            "c": "d"
                        }
                    }`,
		OutDataJSON: `{
                        "A": {
                            "a": "b",
                            "c": "d"
                        }
                    }`,
	}},
}

type R struct {
	A map[string]string
}

func TestGeneratedCode(t *testing.T) {
	tests.Test(t)
}
