// Code generated by generatetestcode.go; DO NOT EDIT.

package multiSchema

import (
	"testing"

	"github.com/heetch/avro/cmd/avrogo/internal/testutil"
)

var tests = testutil.RoundTripTest{
	InSchema: `{
                "name": "R",
                "type": "record",
                "fields": [
                    {
                        "name": "F",
                        "type": {
                            "name": "S",
                            "type": "record",
                            "fields": [
                                {
                                    "name": "G",
                                    "type": "int"
                                }
                            ]
                        }
                    }
                ]
            }`,
	GoType: new(R),
	Subtests: []testutil.RoundTripSubtest{{
		TestName: "main",
		InDataJSON: `{
                        "F": {
                            "G": 99
                        }
                    }`,
		OutDataJSON: `{
                        "F": {
                            "G": 99
                        }
                    }`,
	}},
}

func TestGeneratedCode(t *testing.T) {
	tests.Test(t)
}
