// Code generated by avrogen. DO NOT EDIT.

package multiSchema

import (
	"github.com/heetch/avro/avrotypegen"
)

type R struct {
	F S
}

// AvroRecord implements the avro.AvroRecord interface.
func (R) AvroRecord() avrotypegen.RecordInfo {
	return avrotypegen.RecordInfo{
		Schema: `{"fields":[{"name":"F","type":{"fields":[{"name":"G","type":"int"}],"name":"S","type":"record"}}],"name":"R","type":"record"}`,
		Required: []bool{
			0: true,
		},
	}
}
