// Code generated by avrogen. DO NOT EDIT.

package multiSchema

import (
	"github.com/heetch/avro/avrotypegen"
)

type S struct {
	G int
}

// AvroRecord implements the avro.AvroRecord interface.
func (S) AvroRecord() avrotypegen.RecordInfo {
	return avrotypegen.RecordInfo{
		Schema: `{"fields":[{"name":"G","type":"int"}],"name":"S","type":"record"}`,
		Required: []bool{
			0: true,
		},
	}
}
