// Code generated by generatetestcode.go; DO NOT EDIT.

package goTypeStruct

import (
	"testing"

	"github.com/heetch/avro/avro-generate-go/internal/testutil"
)

var tests = testutil.RoundTripTest{
	InSchema: `{
                "name": "R",
                "type": "record",
                "fields": [
                    {
                        "name": "S",
                        "type": {
                            "name": "T",
                            "type": "record",
                            "fields": [
                                {
                                    "name": "A",
                                    "type": "int"
                                },
                                {
                                    "name": "B",
                                    "type": "string"
                                }
                            ]
                        }
                    }
                ]
            }`,
	GoType: new(R),
	Subtests: []testutil.RoundTripSubtest{{
		TestName: "main",
		InDataJSON: `{
                        "S": {
                            "A": 12345,
                            "B": "hello"
                        }
                    }`,
		OutDataJSON: `{
                        "S": {
                            "A": 12345,
                            "B": "hello"
                        }
                    }`,
	}},
}

type R struct {
	S T
}
type T struct {
	A int
	B string
}

func TestGeneratedCode(t *testing.T) {
	tests.Test(t)
}
