// Code generated by generatetestcode.go; DO NOT EDIT.

package nestedUnionNestedArray

import (
	"testing"

	"github.com/heetch/avro/cmd/avrogo/internal/testutil"
)

var tests = testutil.RoundTripTest{
	InSchema: `{
                "name": "R",
                "type": "record",
                "fields": [
                    {
                        "name": "F",
                        "type": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": [
                                    "null",
                                    "string"
                                ]
                            }
                        }
                    }
                ]
            }`,
	GoType: new(R),
	Subtests: []testutil.RoundTripSubtest{{
		TestName: "main",
		InDataJSON: `{
                        "F": [
                            [
                                null,
                                {
                                    "string": "hello"
                                }
                            ],
                            [
                                {
                                    "string": "goodbye"
                                }
                            ]
                        ]
                    }`,
		OutDataJSON: `{
                        "F": [
                            [
                                null,
                                {
                                    "string": "hello"
                                }
                            ],
                            [
                                {
                                    "string": "goodbye"
                                }
                            ]
                        ]
                    }`,
	}},
}

func TestGeneratedCode(t *testing.T) {
	tests.Test(t)
}
