// Code generated by generatetestcode.go; DO NOT EDIT.

package simpleEnum

import (
	"testing"

	"github.com/rogpeppe/avro/avro-generate-go/internal/testutil"
)

var test = testutil.RoundTripTest{
	InDataJSON: `{
                "E": "b"
            }`,
	OutDataJSON: `{
                "E": "b"
            }`,
	InSchema: `{
                "name": "R",
                "type": "record",
                "fields": [
                    {
                        "name": "E",
                        "type": {
                            "name": "MyEnum",
                            "type": "enum",
                            "symbols": [
                                "a",
                                "b",
                                "c"
                            ]
                        }
                    }
                ]
            }`,
	OutSchema: `{
                "name": "R",
                "type": "record",
                "fields": [
                    {
                        "name": "E",
                        "type": {
                            "name": "MyEnum",
                            "type": "enum",
                            "symbols": [
                                "a",
                                "b",
                                "c"
                            ]
                        }
                    }
                ]
            }`,
	GoType: new(R),
}

func TestGeneratedCode(t *testing.T) {
	test.Test(t)
}
