// Code generated by avrogen. DO NOT EDIT.

package simpleEnum

import "github.com/heetch/avro/avrotypegen"

type MyEnum int

const (
	MyEnumA MyEnum = iota
	MyEnumB
	MyEnumC
)

// TODO UnmarshalText and String methods.

type R struct {
	E MyEnum
}

// AvroRecord implements the avro.AvroRecord interface.
func (R) AvroRecord() avrotypegen.RecordInfo {
	return avrotypegen.RecordInfo{
		Schema: `{"fields":[{"name":"E","type":{"name":"MyEnum","symbols":["a","b","c"],"type":"enum"}}],"name":"R","type":"record"}`,
		Required: []bool{
			0: true,
		},
	}
}

// TODO implement MarshalBinary and UnmarshalBinary methods?
