// Code generated by generatetestcode.go; DO NOT EDIT.

package simpleArray

import (
	"testing"

	"github.com/rogpeppe/avro/avro-generate-go/internal/testutil"
)

var test = testutil.RoundTripTest{
	InDataJSON: `{
                "A": [
                    23,
                    57,
                    444
                ]
            }`,
	OutDataJSON: `{
                "A": [
                    23,
                    57,
                    444
                ]
            }`,
	InSchema: `{
                "name": "R",
                "type": "record",
                "fields": [
                    {
                        "name": "A",
                        "type": {
                            "type": "array",
                            "items": "int"
                        }
                    }
                ]
            }`,
	OutSchema: `{
                "name": "R",
                "type": "record",
                "fields": [
                    {
                        "name": "A",
                        "type": {
                            "type": "array",
                            "items": "int"
                        }
                    }
                ]
            }`,
	GoType: new(R),
}

func TestGeneratedCode(t *testing.T) {
	test.Test(t)
}
