// Code generated by avrogen. DO NOT EDIT.

package simpleArray

import "github.com/rogpeppe/avro"

type R struct {
	A []int
}

// AvroRecord implements the avro.AvroRecord interface.
func (R) AvroRecord() avro.RecordInfo {
	return avro.RecordInfo{
		Schema: `{"fields":[{"name":"A","type":{"items":"int","type":"array"}}],"name":"R","type":"record"}`,
	}
}

// TODO implement MarshalBinary and UnmarshalBinary methods?
