// Code generated by generatetestcode.go; DO NOT EDIT.

package goTypeNilPointer

import (
	"testing"

	"github.com/rogpeppe/avro/avro-generate-go/internal/testutil"
)

var test = testutil.RoundTripTest{
	InDataJSON: `{
                "A": null
            }`,
	OutDataJSON: `{
                "A": null
            }`,
	InSchema: `{
                "name": "TestRecord",
                "type": "record",
                "fields": [
                    {
                        "name": "A",
                        "type": [
                            "null",
                            "int"
                        ]
                    }
                ]
            }`,
	OutSchema: `null`,
	GoType:    new(TestRecord),
}

type TestRecord struct {
	A *int
}

func TestGeneratedCode(t *testing.T) {
	test.Test(t)
}
